name: Build
on:
  pull_request:
    types:
      - synchronize
      - opened
      - labeled
    paths-ignore:
      - ".github/**"
      - "docs/**"
  push:
    branches: [livekit, full-mesh]
    paths-ignore:
      - ".github/**"
      - "docs/**"
  workflow_dispatch:
  
jobs:
  build_element_call:
    uses: ./.github/workflows/element-call.yaml
    with:
      vite_app_version: ${{ github.event.release.tag_name || github.sha }}
