name: Element Call - Build
on:
  workflow_call:
    inputs:
      vite_app_version:
        required: true
        type: string

jobs:
  build:
    name: Build Element Call
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Yarn cache
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          cache: "yarn"
          node-version: "lts/*"
      - name: Install dependencies
        run: "yarn install"
      - name: Build
        run: "yarn run build"
        env:
          VITE_APP_VERSION: ${{ inputs.vite_app_version }}
          NODE_OPTIONS: "--max-old-space-size=4096"
      - name: Upload Artifact
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4
        with:
          name: build-output
          path: dist
          # We'll only use this in a triggered job, then we're done with it
          retention-days: 1
