name: Lint and format
on:
  pull_request: {}
jobs:
  prettier:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Yarn cache
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
      - name: Install dependencies
        run: "yarn install"
      - name: Prettier
        run: "yarn run prettier:check"
      - name: ESLint
        run: "yarn run lint"
